Repository woowa-techcamp-2022/web-todo-6, pull requests merged in 2022-07, with the labels that each got.

#3 [Setting] 클라이언트 배포 테스트
  .gitignore
  client/index.html
  client/package-lock.json
  client/package.json
  package.json
  server/app.js
  server/package-lock.json
  server/package.json
Labels: setting

#5 [Setting] 웹팩 및 sass설정
  .gitignore
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/add.js
  client/src/style/common.scss
  client/src/style/main.scss
  client/src/test.js
  client/webpack.config.js
Labels: setting

#13 [Bug]css background 이미지 절대경로 -> 상대경로로 수정
  client/public/css/app.css
  client/src/style/_todo-aside.scss
  client/src/style/_todo-header.scss
Labels: bug

#19 [Feature] custom element 상태변화에 따른 함수실행 구현
  client/index.html
  client/public/css/app.css
  client/public/css/app.css.map
  client/public/js/bundle.js
  client/src/js/App.js
  client/src/js/TodoCard.js
  client/src/style/_colors.scss
  client/src/style/_todo-card.scss
Labels: feature

#18 [Feature] 사이드 로그 UI 및 섹션 헤더 UI 개발 완료
  client/index.html
  client/public/css/app.css
  client/public/css/app.css.map
  client/public/js/bundle.js
  client/src/js/App.js
  client/src/js/TodoAside.js
  client/src/js/TodoHeader.js
  client/src/js/TodoSection.js
  client/src/style/_common.scss
  client/src/style/_todo-aside.scss
  client/src/style/_todo-section-header.scss
  client/src/style/_todo-section.scss
Labels: feature, design

#21 [Feature] todo-card 컴포넌트 상태별 기능 구현
  client/index.html
  client/public/css/app.css
  client/public/css/app.css.map
  client/public/js/bundle.js
  client/src/js/TodoCard.js
  client/src/style/_colors.scss
  client/src/style/_common.scss
  client/src/style/_todo-card.scss
  client/src/style/_todo-section.scss
Labels: feature

#24 [Refactor] 변수명 수정 했습니다
  client/public/css/app.css
  client/public/css/app.css.map
  client/public/js/bundle.js
  client/src/js/TodoCard.js
  client/src/style/_todo-card.scss
Labels: refactor

#30 [Feature]todo-card 기능 개발
  client/index.html
  client/public/css/app.css
  client/public/css/app.css.map
  client/public/js/bundle.js
  client/src/js/App.js
  client/src/js/TodoCard.js
  client/src/js/TodoMain.js
  client/src/style/_main.scss
  client/src/style/_todo-card.scss
Labels: feature

#26 [Feature] 섹션 간 카드 이동 파란선 표시 되도록 개발
  client/public/js/bundle.js
  client/src/js/App.js
  client/src/js/TodoSection.js
  client/src/style/_common.scss
  client/src/style/_main.scss
Labels: feature

#31 [Feature] 로그 조회 api
  .gitignore
  client/public/css/app.css
  client/public/css/app.css.map
  client/public/js/bundle.js
  server/api/index.js
  server/api/todo.js
  server/api/todoLog.js
  server/api/todoSection.js
  server/app.js
  server/db.js
  server/package-lock.json
  server/package.json
  server/repo/todoLogRepo.js
  server/repo/todoRepo.js
  server/repo/todoSectionRepo.js
Labels: feature

#34 [Feature] 백엔드 API 작업
  .gitignore
  server/api/index.js
  server/api/todo.js
  server/api/todoLog.js
  server/api/todoSection.js
  server/app.js
  server/config/index.js
  server/db.js
  server/middleware/log.js
  server/package-lock.json
  server/package.json
  server/repo/todoLogRepo.js
  server/repo/todoRepo.js
  server/repo/todoSectionRepo.js
Labels: feature

#33 [Bug] 파란색 라인 안보이는 버그 수정
  client/public/js/bundle.js
  client/src/js/App.js
  client/src/js/TodoCard.js
  client/src/js/TodoContainer.js
  client/src/js/TodoMain.js
  client/src/js/TodoSection.js
Labels: bug

#44 [Feature] 프론트 상에서 todo-card 기능(추가, 삭제, 수정) 구현
  client/index.html
  client/public/css/app.css
  client/public/css/app.css.map
  client/public/js/bundle.js
  client/src/js/TodoCard.js
  client/src/js/TodoSection.js
  client/src/style/_todo-card.scss
  server/api/todo.js
  server/api/todoLog.js
  server/api/todoSection.js
  server/app.js
  server/repo/todoLogRepo.js
  server/repo/todoRepo.js
  server/repo/todoSectionRepo.js
Labels: feature

#45 [Feature] todo log list api 적용 완료
  client/index.html
  client/public/js/bundle.js
  client/src/api/config.js
  client/src/api/index.js
  client/src/api/todoLog.js
  client/src/js/TodoAside.js
  server/app.js
  server/db.js
  server/package-lock.json
  server/package.json
  server/repo/todoLogRepo.js
Labels: feature

#47 [Feature] pm2 설정용 스크립트 추가
  client/package-lock.json
  client/package.json
  client/scripts/aws-serve.js
Labels: feature

#49 [Feature] 드래그 드랍 구현 완료
  client/public/css/app.css
  client/public/js/bundle.js
  client/src/js/TodoAside.js
  client/src/js/TodoCard.js
  client/src/js/TodoContainer.js
  client/src/js/TodoMain.js
  client/src/js/TodoSection.js
  client/src/js/util.js
  client/src/style/_todo-card.scss
Labels: feature

#54 [Bug] 카드 이동 중일 때만 파란 줄 표시되도록 수정
  client/public/js/bundle.js
  client/src/js/TodoContainer.js
  client/src/js/TodoSection.js
Labels: bug

#56 [BUG] todo patch 안되는 문제 해결했습니다.
  client/public/js/bundle.js
  client/src/api/config.js
  client/src/api/todoCard.js
  client/src/js/TodoCard.js
Labels: bug

#57 [Feature] 카드 이동 api 연동 완료
  client/index.html
  client/public/js/bundle.js
  client/src/api/todoCard.js
  client/src/api/todoSection.js
  client/src/js/TodoContainer.js
  client/src/js/TodoMain.js
  client/src/js/TodoSection.js
  client/src/js/util.js
  server/api/todo.js
  server/middleware/log.js
  server/repo/todoRepo.js
Labels: feature

#58 [Feature] 백엔드에 setLog 미들웨어 추가
  client/public/js/bundle.js
  client/src/api/todoCard.js
  client/src/js/TodoCard.js
  client/src/js/TodoSection.js
  server/api/todo.js
  server/middleware/log.js
  server/repo/todoRepo.js
Labels: feature

#63 [Bug] 로그 시간표시 수정
  client/public/js/bundle.js
  client/src/js/TodoAside.js
Labels: bug

#65 [Bug] delete API 응답값 안주는 문제 해결
  server/api/todo.js
Labels: bug

#67 [Design]favicon 추가
  client/index.html
  client/public/icon/favicon.ico
Labels: design

#71 [Refactor] 코드 리팩터링
  client/public/js/bundle.js
  client/src/api/index.js
  client/src/api/todoCard.js
  client/src/js/TodoCard.js
  client/src/js/TodoContainer.js
  client/src/js/TodoSection.js
  server/api/todo.js
  server/middleware/log.js
  server/repo/todoLogRepo.js
  server/repo/todoRepo.js
Labels: refactor
